Ignite/Ignite.Web/Controllers/EventsController.cs
using Ignite.Models;
using Ignite.Services.Events;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using System.Security.Claims;

namespace Ignite.Web.Controllers
{
    [AutoValidateAntiforgeryToken]
    public class EventsController : Controller
    {
        private readonly IEventsService eventsService;

        public EventsController(
            IEventsService eventsService)
        {
            this.eventsService = eventsService;
        }

        public IActionResult All()
        {
            var model = eventsService.GetEvents(User.FindFirstValue(ClaimTypes.NameIdentifier));
            return View(model);
        }

        // When a button Subscribe is clicked
        [Authorize]
        public IActionResult Attend(string eventId)
        {
            try
            {
                eventsService.AddUserToEvent(User.FindFirstValue(ClaimTypes.NameIdentifier), eventId);
            }
            catch (Exception)
            {
                return Redirect("/Events/All");
            }

            return Redirect("/Events/All");
        }

        // When a button Unsubscribe is clicked

        [Authorize]
        public IActionResult UnAttend(string eventId)
        {
            try
            {
                eventsService.RemoveUserFromEvent(User.FindFirstValue(ClaimTypes.NameIdentifier), eventId);
            }
            catch (Exception)
            {
                return Redirect("/Events/All");
            }

            return Redirect("/Events/All");
        }

        // When a button More Details is clicked
        public IActionResult Details(string eventId)
        {
            var model = eventsService.GetDetailsOfEvent(User.FindFirstValue(ClaimTypes.NameIdentifier), eventId);
            
            return this.View(model);
        }
    }
}

Ignite/Ignite.Web/Controllers/FitnessesController.cs
using Ignite.Services.Fitnesses;
using Microsoft.AspNetCore.Mvc;

namespace Ignite.Web.Controllers
{
    [AutoValidateAntiforgeryToken]
    public class FitnessesController : Controller
    {
        private readonly IFitnessService fitnessService;

        public FitnessesController(
            IFitnessService fitnessService)
        {
            this.fitnessService = fitnessService;
        }

        public IActionResult All()
        {
            var viewModel = fitnessService.GetAllFitnesses();

            return View(viewModel);
        }
    }
}

Ignite/Ignite.Web/Controllers/HomeController.cs
using Ignite.Models.ParentModels;
using Ignite.Services.Classes;
using Ignite.Services.Events;
using Ignite.Web.Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using System.Diagnostics;
using System.Security.Claims;

namespace Ignite.Web.Controllers
{
    [AutoValidateAntiforgeryToken]
    public class HomeController : Controller
    {
        private readonly IEventsService eventsService;
        private readonly IClassesService classesService;

        public HomeController(
            IEventsService eventsService,
            IClassesService classesService)
        {
            this.eventsService = eventsService;
            this.classesService = classesService;
        }

        public IActionResult Index()
        {
            if (User.Identity.IsAuthenticated)
            {
                return this.Redirect("/Home/IndexLoggedIn");
            }

            return View();
        }

        [Authorize]
        public IActionResult IndexLoggedIn()
        {
            var model = new LoggedInHomePageParentModel
            {
                TopClasses = classesService
                                .GetTopClasses(User.FindFirstValue(ClaimTypes.NameIdentifier),
                                                GlobalConstants.GlobalConstants.TopClassesCount),
                TopEvents = eventsService
                                .GetTopEvents(User.FindFirstValue(ClaimTypes.NameIdentifier),
                                                GlobalConstants.GlobalConstants.TopEventsCount),
            };

            return View(model);
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

Ignite/Ignite.Web/Controllers/SubscriptionsController.cs
using Ignite.Models.ViewModels.Subscriptions;
using Ignite.Services.CartProducts;
using Ignite.Services.Products;
using Ignite.Services.Subscriptions;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using System.Security.Claims;

namespace Ignite.Web.Controllers
{
    [AutoValidateAntiforgeryToken]
    public class SubscriptionsController : Controller
    {
        private readonly ISubscriptionsService subscriptionService;
        private readonly ICartProductsService cartProductsService;
        private readonly IProductsService productsService;

        public SubscriptionsController(
            ISubscriptionsService subscriptionService,
            ICartProductsService cartProductsService,
            IProductsService productsService)
        {
            this.subscriptionService = subscriptionService;
            this.cartProductsService = cartProductsService;
            this.productsService = productsService;
        }

        public IActionResult All()
        {
            var model = subscriptionService
                            .GetAllSubscriptions(User.FindFirstValue(ClaimTypes.NameIdentifier))
                            .OrderBy(s => s.OrderInPage)
                            .ToList();

            foreach (var sub in model)
            {
                sub.Price = productsService.GetProductByGUID(sub.Guid).Price;
            }


            return View(model);
        }

        //When clicking a button Purchase
        [Authorize]
        public IActionResult Buy(string subId)
        {
            try
            {
                cartProductsService.AddToCart(User.FindFirstValue(ClaimTypes.NameIdentifier),
                                       Ignite.Models.Enums.ProductType.Subscription,
                                       subId);
            }
            catch (Exception)
            {
                return Redirect("/Products/CheckOut");
            }

            return Redirect("/Products/CheckOut");
        }
    }
}

Ignite/Ignite.Web/Controllers/UsersController.cs
using Ignite.Services.Users;
using Ignite.Web.Areas.Identity.Pages.Account.Manage;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using static Ignite.Web.Areas.Identity.Pages.Account.Manage.IndexModel;

namespace Ignite.Web.Controllers
{
    [AutoValidateAntiforgeryToken]
    public class UsersController : Controller
    {
        private readonly IUsersService usersService;

        public UsersController(
            IUsersService usersService)
        {
            this.usersService = usersService;
        }

        public IActionResult Login()
        {
            if (User.Identity.IsAuthenticated)
                return this.Redirect("/Home/IndexLoggedIn");

            return this.LocalRedirect("/Identity/Account/Login");
        }
        
        public IActionResult Register()
        {
            if (User.Identity.IsAuthenticated)
                return this.Redirect("/Home/IndexLoggedIn");

            return this.LocalRedirect("/Identity/Account/Register");

        }

        public IActionResult RemoveProfileImage(string userId)
        {
            usersService.RemoveImage(userId);

            return LocalRedirect("/Identity/Account/Manage");
        }
    }
}

Ignite/Ignite.Web/Views/Home/Index.cshtml
@{
    Layout = "";
}


<!DOCTYPE html>
<html lang="en">
<head>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v6.0.0/css/all.css" />
    <link rel="stylesheet" href="~/css/welcomePage.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/Ignite.Web.styles.css" asp-append-version="true" />
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <title>Ignite - Become Better You</title>
</head>
<body>
    <section class="showcase">
    <header>
      <div class="toggle"></div>
    </header>
    <video id="video" src="~/HomePageCinematic.mp4" muted loop autoplay></video>
    
    <div class="overlay">
        <img id="logo" src="~/Logo.png" class="position-absolute bottom-0 end-0"/>
    </div>
    <div class="text">
      <h2>Dare to be great</h2> 
      <h3>Be an inspiration</h3>
      <p>Fitness is not a destination it is a way of life.<br/>
         We bring you the opportunity to become better in your personal, business and social life.</p>
      <a class="btn btn-background-slide" id="login" asp-area="" asp-controller="Users" asp-action="Login">Log In</a>
      <a class="btn btn-background-slide" id="register"  asp-area="" asp-controller="Users" asp-action="Register">Register</a>
      <div class="dropdown">
        <a class="btn dropdown-toggle" href="#" role="button" id="dropdownMenuLink" data-bs-toggle="dropdown" aria-expanded="false">
          MORE
        </a>

        <ul class="dropdown-menu" aria-labelledby="dropdownMenuLink">
          <li><a class="dropdown-item" asp-area="" asp-controller="Fitnesses" asp-action="All">Fitnesses</a></li>
          <li><a class="dropdown-item" asp-area="" asp-controller="Events" asp-action="All">Events</a></li>
          <li><a class="dropdown-item" asp-area="" asp-controller="Subscriptions" asp-action="All">Subscriptions</a></li>
        </ul>
      </div>
    </div>
  </section>
</body>
</html>



  

Ignite/Ignite.Web/Views/Home/IndexLoggedIn.cshtml
@using Ignite.Models.ParentModels
@model LoggedInHomePageParentModel

@{
    ViewData["Title"] = "Privacy Policy";
    int count = 0;
}

<link rel="stylesheet" href="~/css/HomeLoggedIn.css" asp-append-version="true" />

@if (Model.TopEvents.Count > 0)
{
    <h1 class="TopTitle">Top Events</h1>
}

@foreach (var ev in Model.TopEvents)
{
    {
        count++;
    }
    <div class="eventsWidget" style="margin-left:@(80*count)px;">
        <div class="rowEvents">
            <h3>Event - @ev.Name</h3>
            @if (!ev.UserAttends)
            {
                <a href="/Events/Attend?eventId=@ev.Guid" class="btn btn-success buttonn">SUBSCRIBE</a>
            }
            else
            {
                <a href="/Events/UnAttend?eventId=@ev.Guid" class="btn btn-danger buttonn">UNSUBSCRIBE</a>
            }
        </div>
        <h4>Address: @ev.Address</h4>
        <h4>Starts: @ev.StartingDateTime.ToString("dd/MM/yyyy HH:mm")</h4>

        <div class="rowEvents">
            <a class="btn btn-primary moreInfo" href="/Events/Details?eventId=@ev.Guid">
                MORE DETAILS
            </a>

            <div id="peopleAttend">
                <img id="peopleAttendImage" src="~/Images/PeopleAttendIcon.png" \> <strong>@ev.UsersCount</strong>
            </div>
        </div>
    </div>
}

@{
    count = 0;
}

@if (Model.TopClasses.Count > 0)
{
    <h1 class="TopTitle">Top Classes</h1>
}

@foreach (var classs in Model.TopClasses)
{
    {
        count++;
    }

    <div class="classesWidget" style="margin-left:@(80*count)px;">
        <div class="rowClasses">
            <h3>Class - @classs.Name</h3>
        </div>
        <h4>Address: @classs.Address</h4>
        <h4>Starts: @classs.StartingDateTime.ToString("dd/MM/yyyy HH:mm")</h4>

        <div class="rowClasses">
            <a class="btn btn-primary moreInfo" href="/Classes/Details?classId=@classs.Guid">
                MORE DETAILS
            </a>

            <div id="duration">
                <img id="durationImage" src="~/Images/durationClock.png" \> <strong>@classs.DurationInMinutes</strong>
            </div>

            <div id="peopleAttend">
                <img id="peopleAttendImage" src="~/Images/PeopleAttendIcon.png" \> <strong>@classs.UsersCount</strong>
            </div>
            <div>
                <div id="allSeats">
                    SEATS LEFT: <strong>@(classs.AllSeats - classs.UsersCount)</strong>
                </div>
            </div>
        </div>
    </div>
}

<div id="wholeContent">

    <div id="aboutUs" class="whitePart">
        <h2 class="center title">
            ABOUT US
        </h2>

        <p class="center">
            We are helping people to get in shape, commit to a healthier lifestyle and clean their mind.
            <br \>
            Our mission is to deliver easily accessible classes, events and facilities.
            <br \>
            We want to make people to be happy and feel good.
        </p>
    </div>

    <div class="whitePart">
        <h2 class="center title">
            AS THE GREEKS SAY:
        </h2>
        <p class="center">
            "Mens Sana In Corpore Sano"
            <br \>
            =
            <br \>
            "A Healthy Mind In A Healthy Body"
        </p>
    </div>

</div>