Ignite/Ignite.Web/Controllers/ClassesController.cs
using Ignite.Services.Classes;
using Ignite.Services.Products;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using System.Security.Claims;
using Ignite.Services.CartProducts;

namespace Ignite.Web.Controllers
{
    [Authorize]
    public class ClassesController : Controller
    {
        private readonly IClassesService classesService;
        private readonly ICartProductsService cartProductsService;

        public ClassesController(
            IClassesService classesService,
            ICartProductsService cartProductsService)
        {
            this.classesService = classesService;
            this.cartProductsService = cartProductsService;
        }

        public IActionResult All()
        {
            var model = classesService.GetAllClasses(User.FindFirstValue(ClaimTypes.NameIdentifier));
            return View(model);
        }

        public IActionResult Attend(string classId)
        {
            try
            {
                cartProductsService.AddToCart(User.FindFirstValue(ClaimTypes.NameIdentifier),
                                       Ignite.Models.Enums.ProductType.Class,
                                       classId);
            }
            catch (Exception)
            {
                return Redirect("/Products/CheckOut");
            }

            return Redirect("/Products/CheckOut");
        }

        public IActionResult Details(string classId)
        {
            var model = classesService.GetDetailsOfClass(User.FindFirstValue(ClaimTypes.NameIdentifier), classId);

            return this.View(model);
        }
    }
}

Ignite/Ignite.Web/Controllers/EventsController.cs
using Ignite.Models;
using Ignite.Services.Events;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using System.Security.Claims;

namespace Ignite.Web.Controllers
{
    [AutoValidateAntiforgeryToken]
    public class EventsController : Controller
    {
        private readonly IEventsService eventsService;

        public EventsController(
            IEventsService eventsService)
        {
            this.eventsService = eventsService;
        }

        public IActionResult All()
        {
            var model = eventsService.GetEvents(User.FindFirstValue(ClaimTypes.NameIdentifier));
            return View(model);
        }

        // When a button Subscribe is clicked
        [Authorize]
        public IActionResult Attend(string eventId)
        {
            try
            {
                eventsService.AddUserToEvent(User.FindFirstValue(ClaimTypes.NameIdentifier), eventId);
            }
            catch (Exception)
            {
                return Redirect("/Events/All");
            }

            return Redirect("/Events/All");
        }

        // When a button Unsubscribe is clicked

        [Authorize]
        public IActionResult UnAttend(string eventId)
        {
            try
            {
                eventsService.RemoveUserFromEvent(User.FindFirstValue(ClaimTypes.NameIdentifier), eventId);
            }
            catch (Exception)
            {
                return Redirect("/Events/All");
            }

            return Redirect("/Events/All");
        }

        // When a button More Details is clicked
        public IActionResult Details(string eventId)
        {
            var model = eventsService.GetDetailsOfEvent(User.FindFirstValue(ClaimTypes.NameIdentifier), eventId);
            
            return this.View(model);
        }
    }
}

Ignite/Ignite.Web/Controllers/FitnessesController.cs
using Ignite.Services.Fitnesses;
using Microsoft.AspNetCore.Mvc;

namespace Ignite.Web.Controllers
{
    [AutoValidateAntiforgeryToken]
    public class FitnessesController : Controller
    {
        private readonly IFitnessService fitnessService;

        public FitnessesController(
            IFitnessService fitnessService)
        {
            this.fitnessService = fitnessService;
        }

        public IActionResult All()
        {
            var viewModel = fitnessService.GetAllFitnesses();

            return View(viewModel);
        }
    }
}

Ignite/Ignite.Web/Controllers/ProductsController.cs
using Ignite.Services.CartProducts;
using Ignite.Services.Products;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using System.Security.Claims;

namespace Ignite.Web.Controllers
{
    [Authorize]
    [AutoValidateAntiforgeryToken]
    public class ProductsController : Controller
    {
        private readonly ICartProductsService cartProductsService;

        public ProductsController(
            ICartProductsService cartProductsService)
        {
            this.cartProductsService = cartProductsService;
        }

        public IActionResult CheckOut()
        {
            var model = cartProductsService.GetAllProductsForTheUser(User.FindFirstValue(ClaimTypes.NameIdentifier));
            
            return View(model);
        }
        
        public IActionResult Remove(string productId)
        {
            cartProductsService.RemoveFromCart(User.FindFirstValue(ClaimTypes.NameIdentifier), productId);
            return Redirect("CheckOut");
        }

        public IActionResult Purchase()
        {
            cartProductsService.BuyProducts(User.FindFirstValue(ClaimTypes.NameIdentifier));

            return Redirect("CheckOut");
        }

    }
}

Ignite/Ignite.Web/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>Ignite - Become Better You</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/Ignite.Web.styles.css" asp-append-version="true" />
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v6.0.0/css/all.css" />
</head>
<body>
    <header>
        <nav class="navbar autohide fixed-top navbar-expand-sm navbar-toggleable-sm navbar-dark navbarExtension">
            <div class="container-fluid">
                <a id="logoName" asp-area="" asp-controller="Home" asp-action="Index">
                     HOME
                </a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-evenly">
                    <ul class="navbar-nav flex-grow-1 flex-container space-evenly">
                        <a class="flex-item" asp-area="" asp-controller="Fitnesses" asp-action="All">GYMS</a>
                        <a class="flex-item" asp-area="" asp-controller="Events" asp-action="All">EVENTS</a>
                        <a class="flex-item" asp-area="" asp-controller="Subscriptions" asp-action="All">PRICING</a>
                        @if (User.Identity.IsAuthenticated)
                        {
                            <a class="flex-item" asp-area="" asp-controller="Classes" asp-action="All">CLASSES</a>
                            <a class="flex-item" asp-area="" asp-controller="Products" asp-action="CheckOut">
                                <i class="fa-solid fa-cart-shopping fa-lg"></i>
                            </a>
                        }
                    </ul>
                    @if (User.Identity.IsAuthenticated && User.IsInRole("Administrator"))
                    {
                        <div class="dropdown">
                          <a class="btn dropdown-toggle" href="#" role="button" id="dropdownMenuLink" data-bs-toggle="dropdown" aria-expanded="false">
                            ADMINISTRATION
                          </a>

                          <ul class="dropdown-menu" aria-labelledby="dropdownMenuLink">
                            <li><a class="dropdown-item" asp-area="Administration" asp-controller="AdminArticles" asp-action="AllArticles">Articles</a></li>
                            <li><a class="dropdown-item" asp-area="Administration" asp-controller="AdminClasses" asp-action="AllClasses">Classes</a></li>
                            <li><a class="dropdown-item" asp-area="Administration" asp-controller="AdminEvents" asp-action="AllEvents">Events</a></li>
                            <li><a class="dropdown-item" asp-area="Administration" asp-controller="AdminFitnesses" asp-action="AllFitnesses">Fitnesses</a></li>
                          </ul>
                        </div>
                    }
                    <partial name="_LoginPartial" />
                </div>
            </div>
        </nav>
    </header>

        @RenderBody()

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; @DateTime.UtcNow.Year - Ignite
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>